namespace Cthangband.Enumerations
{
    internal enum Reward
    {
        PolySlf = 0,
        GainExp = 1,
        LoseExp = 2,
        GoodObj = 3,
        GreaObj = 4,
        ChaosWp = 5,
        GoodObs = 6,
        GreaObs = 7,
        DreadCurse = 8,
        SummonM = 9,
        HSummon = 10,
        DoHavoc = 11,
        GainAbl = 12,
        LoseAbl = 13,
        RuinAbl = 14,
        AugmAbl = 15,
        PolyWnd = 16,
        HealFul = 17,
        HurtLot = 18,
        CurseWp = 19,
        CurseAr = 20,
        PissOff = 21,
        Wrath = 22,
        Destruct = 23,
        Carnage = 24,
        MassGen = 25,
        DispelC = 26,
        Unused1 = 27,
        Unused2 = 28,
        Unused3 = 29,
        Unused4 = 30,
        Unused5 = 31,
        Ignore = 32,
        SerUnde = 33,
        SerDemo = 34,
        SerMons = 35,
    }
}